# Generated by Django 4.0.4 on 2022-04-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='hello', max_length=255, unique=True, verbose_name='Category safe URL'),
            preserve_default=False,
        ),
    ]
