# Generated by Django 4.0.4 on 2022-04-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_is_active_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.CharField(default='https://res.cloudinary.com/dvgbdioec/image/upload/v1644768223/peacock_yevwhu.png', help_text='Upload a product image link', max_length=255, verbose_name='Image'),
        ),
    ]
